### ISSUE TITLE
app.build callback not called within tests

### ISSUE THREAD

**Issue by pointnet** [pointnet/generate-babelrc#1]
@jonschlinkert, @doowb any idea ?

**Comment by jonschlinkert** [comment]
yes, in [this function](https://github.com/pointnet/generate-babelrc/blob/15da7abddb77d1fff3d2b1603967ee119a0efdcf/generator.js#L50-L74), instead of returning the stream, emit `end`, like this:

``` js
      app.src('./templates/babelrc.tmpl', {cwd: __dirname})
        .pipe(app.renderFile('*'))
        .pipe(app.conflicts(app.cwd))
        .pipe(app.dest(app.cwd))
        .on('error', callback)
        .on('end', callback);
```

**Comment by jonschlinkert** [comment]
great generator btw!

**Comment by pointnet** [comment]
@jonschlinkert thanks! I forgot I was in the ask callback :disappointed: 

I still have a test failing localy, any idea ?

``` shell
  15 passing (11s)                                                                                  
  1 failing                                                                                         

  1) generate-babelrc generator (CLI) should run the default task using the `generate-babelrc` name:
     Error: Cannot find generator: "generate-babelrc"
```

**Comment by jonschlinkert** [comment]
> any idea ?

it's because the generator isn't installed globally (edit: which is the point of the test. I'd love to have a better way to do this). I usually symlink them (this is why I added the symlink code in the tests for one of the generators - but I forgot about the binary, so it won't work as it is currently)

For now, from the root of the project, do:

``` sh
npm link
```

**Comment by pointnet** [comment]
@jonschlinkert found!

As I moved the test file, I'm not symlinking the right folder :disappointed:
